name: Lint and Build
run-name: Lint and Build when push or raise PR

on:
  push:
    branches: ["main", "develop", "feature/*", "!task/*"]

  pull_request_target:
    branches:
      - main
      - develop

jobs:
  lint-and-build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - name: Set up Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20 # Replace with your desired Node.js version
          cache: "npm" # Cache npm dependencies for faster builds

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Run linting
      - name: Run lint
        run: npm run lint

      # Step 5: Run build
      - name: Run build
        run: npm run build