name: markdown-lint
run-name: Linting markdown files
on:
  push:
    branches:
      - main
      - develop
    paths:
      - "**.md" # Match any .md file in any directory
      - "**.mdx"
  pull_request:
    branches:
      - main
      - develop
    paths:
      - "**.md"
      - "**.mdx"
jobs:
  markdown-lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Lint Markdown files
        uses: ./.github/actions/md-lint